name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_GLACIER_06AD3E403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}          # für Preview-Umgebungen & Status-Checks
          action: "upload"
          app_location: "/"          # hier liegen deine HTML/CSS/JS-Dateien
          api_location: ""           # keine Azure Functions
          output_location: ""        # leer, weil du keinen separaten Build-Ordner hast
          skip_app_build: true       # überspringe den Oryx-Build
          skip_api_build: true       # (optional) überspringt das API-Build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_GLACIER_06AD3E403 }}
          action: "close"
          app_location: "/"
